---
- name: Install Packages
  dnf:
    state: installed
    name: '{{ item }}'
  loop:
    - '{{ packages }}'
  become: yes

- name: Ensure Mysql is Running
  service:
    name: mysqld
    state: started
  become: yes

- name: Create Database MySQL
  mysql_db:
    name: '{{wp_db_name}}'
    login_user: root
    state: present

- name: Create User MySQL
  mysql_user:
    login_user: root
    name: '{{wp_db_username }}'
    password: '{{ wp_db_password }}'
    priv: '{{wp_db_name}}.*:ALL'
    state: present
    host: '{{ item }}'
  loop:
    - '{{ wp_host_ip }}'
  no_log: true

- name: 'Configure MySQL for Allow Remote Connections'
  copy:
    src: 'files/my.cnf'
    dest: '/etc/my.cnf'
  become: yes
