---
- hosts: mysql
  handlers:
    - name: restart mysql
      service:
        name: mysqld
        state: restarted
      become: yes

  tasks:
    - name: Install Packages
      dnf:
        state: installed
        name: [
        'mysql-server',
        'python3-PyMySQL'
        ]
      become: yes

    - name: Ensure Mysql is Running
      service:
        name: mysqld
        state: started
      become: yes

    - name: Create Database MySQL
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present

    - name: Create User MySQL
      mysql_user:
        login_user: root
        name: wordpress_user
        password: 12345
        priv: "wordpress_db.*:ALL"
        state: present
        host: "{{ item }}"
      with_items:
        - 'localhost'
        - '127.0.0.1'
        - '192.168.0.135'

    - name: 'Configure MySQL for Allow Remote Connections'
      copy:
        src: '../configs/my.cnf'
        dest: '/etc/my.cnf'
      become: yes