---
- hosts: wordpress
  handlers:
    - name: restart apache
      service:
        name: httpd.service
        state: restarted
      become: yes

  tasks:
    - name: Install Epel and Rmi
      dnf:
        name: [
          'https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm',
          'http://rpms.famillecollet.com/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm'
        ]
        state: installed
      become: yes

    - name: Import EPEL GPG key.
      rpm_key:
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        state: present
      become: yes

    - name: Import remi GPG key.
      rpm_key:
        key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
        state: present
      become: yes

    - name: Set Rmi Version
      shell: dnf module enable php:remi-7.4 -y
      become: yes

    - name: Install Packages
      dnf:
        state: installed
        name: [
        'php',
        'php-cli',
        'php-common',
        'php-fpm',
        'php-dom',
        'php-simplexml',
        'php-xml',
        'php-xmlreader',
        'php-curl',
        'php-date',
        'php-exif',
        'php-filter',
        'php-ftp',
        'php-gd',
        'php-hash',
        'php-iconv',
        'php-json',
        'php-libxml',
        'php-pecl-imagick',
        'php-mbstring',
        'php-mysqlnd',
        'php-openssl',
        'php-pcre',
        'php-posix',
        'php-sockets',
        'php-spl',
        'php-tokenizer',
        'php-zlib',
        'httpd'
        ]
      become: yes

    - name: Change file ownership, group and permissions vagrant for php
      file:
        path: /var/www/html/
        owner: vagrant
        group: vagrant
        mode: "0775"
      become: yes

    - name: Change file ownership, group and permissions vagrant for Apache
      file:
        path: /etc/httpd/conf/httpd.conf
        owner: vagrant
        group: vagrant
      become: yes

    - name: Set php test file
      shell: echo '<?php phpinfo();' >/var/www/html/info.php
      become: yes

    - name: Download wordpress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract wordpress files
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html
        remote_src: yes
      become: yes

    - name: Copy File Wordpress Config
      copy:
        src: "/var/www/html/wordpress/wp-config-sample.php"
        dest: "/var/www/html/wordpress/wp-config.php"
        remote_src: yes
      become: yes

    - name: Configure the wp-config with input database
      replace:
        path: "/var/www/html/wordpress/wp-config.php"
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: "localhost", value: "192.168.0.134" }
        - { regex: "database_name_here", value: "wordpress_db" }
        - { regex: "username_here", value: "wordpress_user" }
        - { regex: "password_here", value: "12345" }
      become: yes

    - name: Change file permissions for wordpress
      file:
        path: /var/www/html/wordpress
        owner: apache
        recurse: yes
      become: yes

    - name: Configure Apache for serve Wordpress
      copy:
        src: '../configs/httpd.conf'
        dest: '/etc/httpd/conf/httpd.conf'
      become: yes
      notify: restart apache